### ISSUE TITLE
[FEATURE] 로그라이크의 요소를 가미하여 게임을 개발할 것을 건의합니다.

### ISSUE THREAD

**Issue by wogns3623** [inureyes/gradios#480]
## 요구사항
* #325 와 연관이 있는 이슈로 게임에 로그라이크의 요소들을 가미하여 개발할 것을 건의합니다.

* 현재도 죽으면 모든것이 초기화되거나 랜덤으로 생성되는 적의 위치. 아이템이 랜덤으로 등장하는 등 로그라이크적 특성들을 어느정도 따라가고 있습니다.

* 여기서 추가적으로 여러가지 다른 패턴을 가진 적들을 만들고, 스테이지마다 적들의 종류가 랜덤하게 구성되거나(#330),  게임 The Binding of Isaac처럼 여러 가지 아이템이 존재하고, 아이템끼리의 시너지가 존재하는 등(정확히 로그라이트의 특성으로 볼 수는 없지만) 게임에 로그라이트 요소들을 집어넣으면 게임이 재미있어질 것이라고 생각합니다.

* 아이템끼리의 시너지에 대해 예를 들면 플레이어 기체의 총알이 납작해지는 대신 속도가 느려지는 아이템과 기체의 공격이 레이저형태로 바뀌는 아이템을 먹으면 레이저의 굵기가 증가하지만 레이저의 충전속도가 느려지거나, 기체의 공격이 적에게 맞으면 범위공격이 되는 아이템과 적이 총알을 맞으면 주기적으로 피해를 입는 아이템을 먹으면 범위공격에 맞은 적들 또한 지속적으로 피해를 입는 등을 말합니다.

* 또한 이전에 #400 에서 언급된 필살기 스킬을 사용 아이템의 개념으로 만들어 특정 사용아이템을 먹은 뒤 충전하여 사용하는 식으로 하면 어떨까 생각합니다.

* 따라서 스테이지마다 랜덤하게 등장하는 다양한 패턴의 적들, 현재의 단순한 공격속도 증가, 이동속도 증가 아이템과는 다른 다양한 효과의 아이템들과 아이템끼리의 시너지, 아이템을 먹었을 때 기체의 외형 변화 등의 기능을 추가하였으면 합니다.

* 또한 현재의 스테이지 사이의 간격은 매우 짧은 편입니다. #368 이슈의 내용처럼 기체가 점점 왼쪽에서 오른쪽으로 이동하면서 스테이지를 진행하는 방식을 채택하여 스테이지의 볼륨, 즉 각 스테이지마다의 플레이타임을 늘렸으면 합니다.

* 만약 위의 아이템들이 추가된다면 아이템의 등장 방식 또한 바뀌여야 합니다. 아이템 하나하나의 밸류가 낮은 경우에는 기존의 방식이 좋지만 위에서 언급된 아이템들은 그렇지 않기 때문에 하트 등은 기존과 같이 적 기체를 죽였을 때 나오게 만들고, 스테이지마다 1~2개의 상자가 등장하고 상자를 깨서 아이템을 얻는 식으로 아이템의 출현 빈도를 낮추는 것이 좋을 것 같습니다.

### 적 기체 관련

- [x] 적 기체에 체력 개념 도입(#365)

- [x] 적 기체의 다양화(#330 & #368)

- [ ] 각각의 적 기체마다 공격/이동 패턴 추가(#330)

- [x] 스테이지마다 랜덤한 종류의 적 기체 등장

- [x] 스테이지의 적, 아이템 등이 점점 오른쪽에서 왼쪽으로 이동(#368)

- [x] 스테이지의 볼륨(길이) 늘리기

### 아이템 관련

- [x] 여러가지 기체에 영향을 주는 아이템 추가

- [x] 아이템들 간의 시너지 구현

- [ ] 충전하여 사용할 수 있는 사용 아이템 추가

- [x] 아이템의 등장 방식 수정

### 그 외 필수적으로 필요한 refactoring 목록

- [x] bullet에 관련된 함수 분리하기

- [x] player에 대한 함수들 분리하기

- [ ] enemy에 대한 함수들 분리하기

**Comment by wogns3623** [comment]
기본적으로 구현하면 좋을 것 같은 아이템들을 생각해보았는데
공격 속도 증가
공격 데미지 증가
총알을 레이저로 바꾸는 아이템
충알이 두배로 나가는 아이템
총알이 기체 주변을 돌게 되는 아이템
총알대신 철퇴를 쏘는 아이템
총알의 크기가 커지는 아이템
기체의 크기가 작아지는 아이템

등을 생각해봤는데 있으면 좋을 것 같은 아이템들을 얘기해주시면 감사하겠습니다.

추가로 아이템의 밸런스 조정을 위해 아이템에 좋은 효과와 안좋은 효과를 동시에 넣는 것도 좋을 것 같습니다.(ex) 데미지가 두배로 증가하지만 기체의 크기또한 증가함)

**Comment by HochulHwang** [comment]
적 기체 관련 "스테이지의 볼륨 늘리기"는 구체적으로 어떤 것을 말씀하시는 건가요?

**Comment by wogns3623** [comment]
스테이지의 길이를 늘리는 것을 말하고싶었는데 표현이 잘 전달되지 않았나보나요ㅠ

**Comment by HochulHwang** [comment]
아닙니다~ 감사합니다 :)

**Comment by doublik** [comment]
기존방식은 냅두고 새로운 모드를 만들어서 거기에 적용시키는 건 어떨까요?

**Comment by wogns3623** [comment]
그러면 브랜치를 새로 파서 거기서 작업을 진행할까요?

**Comment by doublik** [comment]
#484 블루 레이저빔 이미지 제작후 추가.

**Comment by wogns3623** [comment]
마스터 브랜치에 해당 내용들이 반영되었으므로 이 이슈는 닫도록 하겠습니다.
